proyecto-laravel/blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Input;
use App\Region;

Route::get('/', function () {
	return view('welcome');
});

Route::get('auth/login', function (){
	return view('auth/login');
});

Route::get('ventajas_premium', function (){
	return view('ventajas_premium');
})->name('ventajasPremium');

Route::get('pago_premium', function (){
	return view('pago_premium');
})->name('pagoPremium');


Route::get('login/{service}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{service}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('verificaCorreo', 'Auth\RegisterController@verificaCorreo')->name('verificaCorreo');
Route::get('verify/{email}/{verifyToken}','Auth\RegisterController@envioHecho')->name('envioHecho');

Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/password/reset/{token}/{email}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::get('pagar_premium', 'PagosController@pagar')->name('pagarPremium');

Auth::routes();


Route::get('/eventos', 'EventosController@index')->name('eventos');

Route::get('edit_evento', function(){
	return view('edit_eventos');
});

Route::group(['prefix' => 'user'], function(){
	Route::resource('eventos', 'EventosController', ['names' => []]);
});

Route::get('eventos/{id}/destroy', 'EventosController@destroy')->name('eventos.destroy');
Route::get('misEventos', 'EventosController@misEventos')->name('misEventos');
Route::get('eventos/aprobar', 'EventosController@aprobarEventos')->name('aprobarEventos');

Route::get('eventos/{id}/aprobar', 'EventosController@eventoAprobar')->name('eventos.aprobar');


Route::get('dropdown_region', function(){
	$id = Input::get('option');
	$provincias = Region::find($id)->provincias;
	return $provincias->pluck('nombre', 'id');
});

Route::get('dropdown_provincia', function(){
	$id = Input::get('option');
	$comunas = App\Provincia::find($id)->comunas;
	return $comunas->pluck('nombre', 'id');
});

proyecto-laravel/blog/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', 'Default') - Panoraming </title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ asset('bootstrap-social.css') }}" rel="stylesheet">

</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    <img alt="Panoraming" src="{{ asset('images/ico.png') }}"  width="64" class="img-circle"> 
                    Panoraming
                    @if (Auth::check() and Auth::user()->type == 'premium')
                        Premium
                    @endif
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ route('login') }}">Ingresar</a></li>
                        <li><a href="{{ route('register') }}">Registrarse</a></li>
                    @else
                        <li>
                            <form action="{{ route('eventos') }}" class="navbar-form navbar-left" method="GET">
                                <div class="form-group">
                                    <input name="buscar" type="text" class="form-control" placeholder="Buscar Evento">
                                </div>
                                <button type="submit" class="btn btn-default">Buscar</button>
                            </form>
                        </li>
                        @if( Auth::user()->type == 'admin' )

                        <li><a href="{{ route('aprobarEventos') }}">Aprobar Eventos</a></li>

                        @endif
                        <li><a href="{{ route('eventos')}}">Eventos</a></li>
                        @if (Request::url() != route('eventos.create'))
                            <li><a href="{{ route('eventos.create') }}">Crear Evento</a></li>
                        @endif
                        <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <img src={{Auth::user()->avatar}} style="width:30px" class="img-circle">
                                    &nbsp; {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="#">
                                        Mi Perfil
                                    </a>
                                    <a href="{{ route('misEventos')}}">
                                        Mis eventos
                                    </a>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Salir
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>  
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4>@yield('title', 'Default')</h4>
                        </div>
                        <div class="panel-body">
                            @include('flash::message')
                            @yield('content')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
<script>
    $('div.alert').not('.alert-important').delay(3000).fadeOut(350);
</script>
</body>

</html>