proyecto-laravel/blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Input;
use App\Region;

Route::get('/', function () {
	return view('welcome');
});

Route::get('auth/login', function (){
	return view('auth/login');
});

Route::get('ventajas_premium', function (){
	return view('ventajas_premium');
})->name('ventajasPremium');

Route::get('pago_premium', function (){
	return view('pago_premium');
})->name('pagoPremium');


Route::get('login/{service}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{service}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('verificaCorreo', 'Auth\RegisterController@verificaCorreo')->name('verificaCorreo');
Route::get('verify/{email}/{verifyToken}','Auth\RegisterController@envioHecho')->name('envioHecho');

Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset');
Route::get('/password/reset/{token}/{email}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::get('pagar_premium', 'PagosController@pagar')->name('pagarPremium');

Auth::routes();


Route::get('/eventos', 'EventosController@index')->name('eventos');

Route::get('edit_evento', function(){
	return view('edit_eventos');
});

Route::group(['prefix' => 'user'], function(){
	Route::resource('eventos', 'EventosController', ['names' => []]);
});

Route::get('eventos/{id}/destroy', 'EventosController@destroy')->name('eventos.destroy');
Route::get('misEventos', 'EventosController@misEventos')->name('misEventos');
Route::get('eventos/aprobar', 'EventosController@aprobarEventos')->name('aprobarEventos');

Route::get('eventos/{id}/aprobar', 'EventosController@eventoAprobar')->name('eventos.aprobar');


Route::get('dropdown_region', function(){
	$id = Input::get('option');
	$provincias = Region::find($id)->provincias;
	return $provincias->pluck('nombre', 'id');
});

Route::get('dropdown_provincia', function(){
	$id = Input::get('option');
	$comunas = App\Provincia::find($id)->comunas;
	return $comunas->pluck('nombre', 'id');
});

proyecto-laravel/blog/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 
        'email', 
        'password', 
        'verifyToken', 
        'type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function eventos()
    {
        return $this->hasMany('App\Evento');
    }
}

proyecto-laravel/blog/resources/views/user/crear_evento.blade.php
@extends('layouts.app')

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $('#region').change(function(){
            $.get("{{ url('dropdown_region')}}",
            { option: $(this).val() },
            function(data) {
                $('#provincia').empty();
                $.each(data, function(key, element) {
                    $('#provincia').append("<option value='" + key + "'>" + element + "</option>");
                });
            });
        });
    });     
</script>
<script>
    $(document).ready(function(){
        $('#provincia').change(function(){
            $.get("{{ url('dropdown_provincia')}}",
            { option: $(this).val() },
            function(data) {
                $('#comuna').empty();
                $.each(data, function(key, element) {
                    $('#comuna').append("<option value='" + key + "'>" + element + "</option>");
                });
            });
        });
    });     
</script>
@section('title','Crear Evento')
@section('content')

    <form class="form-horizontal" id="form-crear-evento" method="POST" action="{{ route('eventos.store') }}" enctype="multipart/form-data">
        {{ csrf_field() }}

        <div class="form-group">
            <label for="nombre" class="col-md-4 control-label">Nombre</label>

            <div class="col-md-6">
                <input id="nombre" type="text" class="form-control" name="nombre" value="{{ old('nombre') }}" required autofocus>
                @if ($errors->has('nombre'))
                    <span class="help-block">
                        <strong>{{ $errors->first('nombre') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group">
            <label for="region" class="col-md-4 control-label">Region</label>

            <div class="col-md-6">
                <select class="selectpicker" form="form-crear-evento" id="region" name="region" required>
                    <option value= "" selected disabled>Seleccione Region</option>
                    @foreach (App\Region::all() as $region)
                        <option value="{{$region->id}}">{{$region->nombre}}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="provincia" class="col-md-4 control-label">Provincia</label>

            <div class="col-md-6">
                <select class="selectpicker" form="form-crear-evento" id="provincia" name="provincia" required>
                    <option value= "" selected disabled>Seleccione Provincia</option>    
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="comuna" class="col-md-4 control-label">Comuna</label>

            <div class="col-md-6">
                <select class="selectpicker" form="form-crear-evento" id="comuna" name="comuna" required>
                    <option value= "" selected disabled>Seleccione Comuna</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="direccion" class="col-md-4 control-label">Dirección</label>

            <div class="col-md-6">
                <input id="direccion" type="text" class="form-control" name="direccion" value="{{ old('direccion') }}" required>
                @if ($errors->has('direccion'))
                    <span class="help-block">
                        <strong>{{ $errors->first('direccion') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group">
            <label for="fecha" class="col-md-4 control-label">Fecha</label>

            <div class="col-md-6">
                <input type="date" name="fecha" required>
            </div>
        </div>

        <div class="form-group">
            <label for="hora" class="col-md-4 control-label">Hora</label>

            <div class="col-md-6">
                <input type="time" name="hora" required>
            </div>

        </div>

        @if(Auth::check() and Auth::user()->type == 'premium')
        <div class="form-group">
            <label for="url" class="col-md-4 control-label">Sitio Pago/Reserva</label>

            <div class="col-md-6">
                <input id="url" type="url" class="form-control" name="url" value="{{ old('url') }}" >
            </div>
        </div>
        @endif

        <div class="form-group">
            <label for="descripcion" class="col-md-4 control-label">Descripción</label>

            <div class="col-md-6">
                <textarea rows="4" cols="50" name="descripcion" form="form-crear-evento"></textarea>
                @if ($errors->has('descripcion'))
                    <span class="help-block">
                        <strong>{{ $errors->first('descripcion') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        @if(Auth::check() and Auth::user()->type == 'premium')
        <div class="form-group">
            <label for="afiche" class="col-md-4 control-label">Afiche</label>

            <div class="col-md-6">
                <input id="afiche" type="file" class="form-control" name="afiche" value="{{ old('afiche') }}">
                @if ($errors->has('afiche'))
                    <span class="help-block">
                        <strong>{{ $errors->first('afiche') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        @endif
        
        <div class="form-group">
            <div class="col-md-6 col-md-offset-4">
                <button type="submit" class="btn btn-primary">
                    Crear
                </button>
            </div>
        </div>
    </form>

@endsection

proyecto-laravel/blog/resources/views/user/edit_eventos.blade.php
@extends('layouts.app')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $('#region').change(function(){
            $.get("{{ url('dropdown_region')}}",
            { option: $(this).val() },
            function(data) {
                $('#provincia').empty();
                $.each(data, function(key, element) {
                    $('#provincia').append("<option value='" + key + "'>" + element + "</option>");
                });
            });
        });
    });     
</script>
<script>
    $(document).ready(function(){
        $('#provincia').change(function(){
            $.get("{{ url('dropdown_provincia')}}",
            { option: $(this).val() },
            function(data) {
                $('#comuna').empty();
                $.each(data, function(key, element) {
                    $('#comuna').append("<option value='" + key + "'>" + element + "</option>");
                });
            });
        });
    });     
</script>
@section('title', 'Editar Evento: ' . $evento->nombre)
@section('content')
	<form  action="{{ route('eventos.update', $evento->id) }}"  class="form-horizontal" method="POST" enctype="multipart/form-data" id="form-edit-evento">
        <input type="hidden" name="_method" value="PUT">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">

        <div class="form-group">
            <label for="nombre" class="col-md-4 control-label">Nombre</label>

            <div class="col-md-6">
                <input id="nombre" type="text" class="form-control" name="nombre" value="{{$evento->nombre}}" required autofocus >
                @if ($errors->has('nombre'))
                    <span class="help-block">
                        <strong>{{ $errors->first('nombre') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group">
            <label for="region" class="col-md-4 control-label">Region</label>

            <div class="col-md-6">
                <select class="selectpicker" form="form-edit-evento" id="region" name="region" required>
                    <option value= "" selected disabled>Seleccione Region</option>
                    @foreach (App\Region::all() as $region)
                        <option value="{{ $region->id }}">{{ $region->nombre }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="provincia" class="col-md-4 control-label">Provincia</label>

            <div class="col-md-6">
                <select class="selectpicker" form="form-edit-evento" id="provincia" name="provincia" required>
                    <option value= "" selected disabled>Seleccione Provincia</option>    
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="comuna" class="col-md-4 control-label">Comuna</label>

            <div class="col-md-6">
                <select class="selectpicker" form="form-edit-evento" id="comuna" name="comuna" required>
                    <option value= "" selected disabled>Seleccione Comuna</option>
                </select>
            </div>
        </div>
       
        <div class="form-group">
            <label for="direccion" class="col-md-4 control-label">Dirección</label>

            <div class="col-md-6">
                <input id="direccion" type="text" class="form-control" name="direccion" value="{{ $evento->direccion }}" required autofocus>
                @if ($errors->has('direccion'))
                    <span class="help-block">
                        <strong>{{ $errors->first('direccion') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group">
            <label for="fecha" class="col-md-4 control-label">Fecha</label>

            <div class="col-md-6">
                <input type="date" name="fecha" required value="{{$evento->fecha}}">
            </div>
        </div>

        <div class="form-group">
            <label for="hora" class="col-md-4 control-label">Hora</label>

            <div class="col-md-6">
                <input type="time" name="hora" value="{{ $evento->hora }}" required>
            </div>

        </div>

        @if(Auth::check() and Auth::user()->type == 'premium')
        <div class="form-group">
            <label for="url" class="col-md-4 control-label">Sitio Pago/Reserva</label>

            <div class="col-md-6">
                <input id="url" type="url" class="form-control" name="url" value="{{ $evento->url }}" autofocus>
            </div>
        </div>
        @endif

        <div class="form-group">
            <label for="descripcion" class="col-md-4 control-label">Descripción</label>

            <div class="col-md-6">
                <textarea rows="4" cols="50" name="descripcion" form="form-edit-evento" >{{ $evento->descripcion }}</textarea>
                @if ($errors->has('descripcion'))
                    <span class="help-block">
                        <strong>{{ $errors->first('descripcion') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        @if(Auth::check() and Auth::user()->type == 'premium')
        <div class="form-group">
            <label for="afiche" class="col-md-4 control-label">Afiche</label>

            <div class="col-md-6">
                <input id="afiche" type="file" class="form-control" name="afiche" value="{{ old('afiche') }}" autofocus>
                @if ($errors->has('afiche'))
                    <span class="help-block">
                        <strong>{{ $errors->first('afiche') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        @endif
        
        <div class="form-group">
            <div class="col-md-6 col-md-offset-4">
                <button type="submit" class="btn btn-primary">
                    Editar
                </button>
            </div>
        </div>
    </form>
@endsection

proyecto-laravel/blog/resources/views/user/info_evento.blade.php
@extends('layouts.app')
@section('title', 'Evento: ' . $evento->nombre)
@section('content')
	<div class="row">
		<div class="col-xs-12 col-md-8">
			<img src="{{ Storage::url($evento->afiche) }}" class="img-responsive img-thumbnail" alt="Responsive image" height="350px" width="500px">
		</div>
		<div class="col-xs-6 col-md-4">
			<div class="panel panel-info">
				<div class="panel-body">
					<i class="fa fa-calendar" aria-hidden="true"></i>
					{{$evento->fecha}}
					<br><br>
					<i class="fa fa-clock-o" aria-hidden="true"></i>
					{{$evento->hora}}
					<br><br>
					<i class="fa fa-map-marker" aria-hidden="true"></i>
					{{$evento->direccion}}<br><br>
					{{$evento->comuna->nombre}}, {{$evento->provincia->nombre}},&nbsp; 
					@if ($evento->region_id=='7')
						Región 	
					
					@elseif ($evento->region_id=='8' or $evento->region_id=='9' or $evento->region_id=='10')
						Región del 
					
					@else 
						Región de 
					
					@endif
					{{$evento->region->nombre}}
					<br><br>
					<i class="fa fa-external-link" aria-hidden="true"></i>
					<a href="{{$evento->url}}" target="_blank">{{$evento->url}}</a>
				</div>
			</div>
		</div>
	</div>
	<br>
	<div class="panel panel-info">
		<div class="panel-heading">
		    <h5 class="panel-title">Descripcion</h5>
		</div>
		<div class="panel-body">
		    {{$evento->descripcion}}
		</div>
	</div>
	
	@if(!$evento->estado)
	<div class="panel panel-warning">
		<div class="panel-heading">
		    <h5 class="panel-title">Inactivo</h5>
		</div>
		<div class="panel-body">
			<h3>Pendiente de Aprobación</h3>
		</div>
	</div>
	@else
		<h3>Comentarios</h3>

		@if (!Auth::check())
			Para ver los comentarios debes estar logueado
		@endif

		@if (Auth::check())
		<div id="disqus_thread"></div>
		@endif
		<script>
			/**
			*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
			*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
			/*
			var disqus_config = function () {
			this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
			this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
			};
			*/
			(function() { // DON'T EDIT BELOW THIS LINE
			var d = document, s = d.createElement('script');
			s.src = 'https://panoraming.disqus.com/embed.js';
			s.setAttribute('data-timestamp', +new Date());
			(d.head || d.body).appendChild(s);
			})();
		</script>
		<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	@endif
                        
@endsection

proyecto-laravel/blog/resources/views/user/mis_eventos.blade.php
@extends('layouts.app')
@section('content')
@section('title', 'Mis Eventos' )

<div class="row">

    @if($events->isEmpty())
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-body">
                    <h3 align="center">No haz creado eventos</h3>
                </div>
            </div>
        </div>
    @endif

    @foreach($events as $event)
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            
            <a href="{{ route('eventos.show', $event->id) }}"><img src="{{ Storage::url($event->afiche) }}" ></a>
            
            <div class="caption">
                <h3>{{ $event->nombre }}</h3>
                <p><i class="fa fa-calendar" aria-hidden="true"></i> {{ $event->fecha }}</p>
                <p><i class="fa fa-map-marker" aria-hidden="true"></i> {{ $event->comuna->nombre }}</p>
                @if(!$event->estado)
                    <div class="panel panel-warning">Pendiente de Aprobación</div>
                @endif
                <p>
                    <a href="{{ route('eventos.edit', $event->id) }}" class="btn btn-primary" role="button">Editar</a> 
                    <a href="{{ route('eventos.destroy', $event->id) }}" class="btn btn-danger" role="button" onclick="return confirm('Seguro que quieres eliminar este evento?')">Eliminar</a>
                </p>
            </div>
        </div>
    </div>
    @endforeach
</div>

<div align="center">
    {!! $events->render() !!}
</div>

@endsection